# Generated by Django 5.1.2 on 2025-08-08 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ndb_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='qr_code_id',
        ),
    ]
